use super::{Attr, Attribute, AttributeValue, StaticAttr};
use crate::view::{Position, ToTemplate};
use std::fmt::Debug;
use web_sys::Element;

pub trait AttributeKey {
    const KEY: &'static str;
}

macro_rules! attributes {
	($($key:ident $html:literal),* $(,)?) => {
        paste::paste! {
            $(
                pub fn $key<V>(value: V) -> Attr<[<$key:camel>], V>
				where V: AttributeValue + std::fmt::Debug
                {
                    Attr([<$key:camel>], value)
                }

				#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
				pub struct [<$key:camel>];

				impl AttributeKey for [<$key:camel>] {
					const KEY: &'static str = $html;
				}
            )*
		}
    }
}

// TODO attribute names with underscores should be kebab-cased
attributes! {
    accept_charset "accept-charset",
    accept "accept",
    accesskey "accesskey",
    action "action",
    align "align",
    allow "allow",
    alt "alt",
    aria_atomic "aria-atomic",
    aria_busy "aria-busy",
    aria_controls "aria-controls",
    aria_current "aria-current",
    aria_describedby "aria-describedby",
    aria_description "aria-description",
    aria_details "aria-details",
    aria_disabled "aria-disabled",
    aria_dropeffect "aria-dropeffect",
    aria_errormessage "aria-errormessage",
    aria_flowto "aria-flowto",
    aria_grabbed "aria-grabbed",
    aria_haspopup "aria-haspopup",
    aria_hidden "aria-hidden",
    aria_invalid "aria-invalid",
    aria_keyshortcuts "aria-keyshortcuts",
    aria_label "aria-label",
    aria_labelledby "aria-labelledby",
    aria_live "aria-live",
    aria_owns "aria-owns",
    aria_relevant "aria-relevant",
    aria_roledescription "aria-roledescription",
    r#async "async",
    autocapitalize "autocapitalize",
    autocomplete "autocomplete",
    autofocus "autofocus",
    autoplay "autoplay",
    background "background",
    bgcolor "bgcolor",
    border "border",
    buffered "buffered",
    capture "capture",
    challenge "challenge",
    charset "charset",
    checked "checked",
    cite "cite",
    //class "class",
    code "code",
    codebase "codebase",
    color "color",
    cols "cols",
    colspan "colspan",
    content "content",
    contenteditable "contenteditable",
    contextmenu "contextmenu",
    controls "controls",
    coords "coords",
    crossorigin "crossorigin",
    csp "csp",
    data "data",
    datetime "datetime",
    decoding "decoding",
    default "default",
    defer "defer",
    dir "dir",
    dirname "dirname",
    disabled "disabled",
    download "download",
    draggable "draggable",
    enctype "enctype",
    enterkeyhint "enterkeyhint",
    r#for "for",
    form "form",
    formaction "formaction",
    formenctype "formenctype",
    formmethod "formmethod",
    formnovalidate "formnovalidate",
    formtarget "formtarget",
    headers "headers",
    height "height",
    hidden "hidden",
    high "high",
    href "href",
    hreflang "hreflang",
    http_equiv "http-equiv",
    icon "icon",
    id "id",
    importance "importance",
    inputmode "inputmode",
    integrity "integrity",
    intrinsicsize "intrinsicsize",
    ismap "ismap",
    itemprop "itemprop",
    keytype "keytype",
    kind "kind",
    label "label",
    lang "lang",
    language "language",
    list "list",
    loading "loading",
    r#loop "loop",
    low "low",
    manifest "manifest",
    max "max",
    maxlength "maxlength",
    media "media",
    method "method",
    min "min",
    minlength "minlength",
    multiple "multiple",
    muted "muted",
    name "name",
    novalidate "novalidate",
    open "open",
    optimum "optimum",
    pattern "pattern",
    ping "ping",
    placeholder "placeholder",
    poster "poster",
    preload "preload",
    radiogroup "radiogroup",
    readonly "readonly",
    referrerpolicy "referrerpolicy",
    rel "rel",
    required "required",
    reversed "reversed",
    role "role",
    rows "rows",
    rowspan "rowspan",
    sandbox "sandbox",
    scope "scope",
    scoped "scoped",
    selected "selected",
    shape "shape",
    size "size",
    sizes "sizes",
    slot "slot",
    span "span",
    spellcheck "spellcheck",
    src "src",
    srcdoc "srcdoc",
    srclang "srclang",
    srcset "srcset",
    start "start",
    step "step",
    style "style",
    summary "summary",
    tabindex "tabindex",
    target "target",
    title "title",
    translate "translate",
    r#type "type",
    usemap "usemap",
    value "value",
    width "width",
    wrap "wrap",
}
